//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint
    {
        public int PK_iComplaintsID { get; set; }
        public int FK_iSupplierID { get; set; }
        public string sUserName { get; set; }
        public string sReason { get; set; }
    
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
